fix: No warn for token unused
Otherwise, for projects where FS1182 is an error, developers will get `x.g.fs(19,61): error FS1182: The value 'token' is unused`.